version: '3.9'

services:
  postgres1:
    image: jgiannuzzi/postgres-bdr
    container_name: postgres1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bdr
      POSTGRES_PASSWORD: bdrpass
      POSTGRES_DB: bdrdb
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    volumes:
      - ./init-scripts/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - ./init-scripts/node1/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init-scripts/node1/finalize-node1.sh:/finalize-node1.sh
    networks:
      - bdrnet

  postgres2:
    image: jgiannuzzi/postgres-bdr
    container_name: postgres2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: bdr
      POSTGRES_PASSWORD: bdrpass
      POSTGRES_DB: bdrdb
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    volumes:
      - ./init-scripts/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - ./init-scripts/node2/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - bdrnet

  haproxy:
    image: haproxy:2.9
    container_name: haproxy
    networks:
      - bdrnet
    ports:
      - "5000:5000" # HAProxy will listen here for Postgres clients
      - "7000:7000" # Optional: web UI or debug
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - postgres1
      - postgres2
volumes:
  pg1_data:
  pg2_data:

networks:
  bdrnet:
    driver: bridge
