version: '3.9'

services:
  postgres1:
    image: jgiannuzzi/postgres-bdr
    container_name: postgres1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bdr
      POSTGRES_PASSWORD: bdrpass
      POSTGRES_DB: bdrdb
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    volumes:
      - pg1_data:/var/lib/postgresql/data
      - ./init-scripts/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - ./init-scripts/node1/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - bdrnet

  postgres2:
    image: jgiannuzzi/postgres-bdr
    container_name: postgres2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: bdr
      POSTGRES_PASSWORD: bdrpass
      POSTGRES_DB: bdrdb
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    volumes:
      - pg2_data:/var/lib/postgresql/data
      - ./init-scripts/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - ./init-scripts/node2/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - bdrnet

volumes:
  pg1_data:
  pg2_data:

networks:
  bdrnet:
    driver: bridge
